backend:
  name: git-gateway
  branch: v2 # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Imagem', name: 'image', widget: 'image' }
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Descrição', name: 'description', widget: 'string' }
      - { label: 'Conteúdo', name: 'body', widget: 'markdown' }

  - name: 'testimonial'
    label: 'Depoimentos'
    folder: 'content/testimonial'
    summary: '{{name}} - {{company}}'
    format: 'frontmatter'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Imagem', name: 'image', widget: 'image' }
      - { label: 'Nome', name: 'name', widget: 'string' }
      - { label: 'Empresa', name: 'company', widget: 'string' }
      - { label: 'Depoimento', name: 'content', widget: 'string' }
