backend:
  name: git-gateway
  branch: v2 # Branch to update (optional; defaults to master)

site_url: https://v2.kofe.design
display_url: https://v2.kofe.design
media_folder: static/images
public_folder: /images
locale: pt
slug:
  encoding: 'ascii'
  clean_accents: true

collections:
  - name: 'highlights'
    label: 'Destaques'
    folder: 'content/highlights'
    summary: '({{order}}) {{description}}'
    format: 'frontmatter'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Imagem', name: 'image', widget: 'image' }
      - { label: 'Descrição', name: 'description', widget: 'string' }
      - { label: 'Ordem', name: 'order', widget: 'number', value_type: 'int', min: 1 }

  - name: 'testimonial'
    label: 'Depoimentos'
    folder: 'content/testimonial'
    summary: '({{order}}) {{name}} - {{company}}'
    format: 'frontmatter'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Imagem', name: 'image', widget: 'image' }
      - { label: 'Nome', name: 'name', widget: 'string' }
      - { label: 'Empresa', name: 'company', widget: 'string' }
      - { label: 'Depoimento', name: 'content', widget: 'string' }
      - { label: 'Ordem', name: 'order', widget: 'number', value_type: 'int', min: 1 }

  - name: 'projects'
    label: 'Projetos'
    folder: 'content/projects'
    summary: '({{order}}) {{title}}'
    format: 'frontmatter'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Imagem', name: 'image', widget: 'image' }
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Ordem', name: 'order', widget: 'number', value_type: 'int', min: 1 }

  - name: 'clients'
    label: 'Clientes'
    folder: 'content/clients'
    summary: '({{order}}) {{title}}'
    format: 'frontmatter'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Imagem', name: 'image', widget: 'image' }
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Ordem', name: 'order', widget: 'number', value_type: 'int', min: 1 }

  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Imagem', name: 'image', widget: 'image' }
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Descrição', name: 'description', widget: 'string' }
      - { label: 'Conteúdo', name: 'body', widget: 'markdown' }
